[package]
name = "alpin-cv"
version = "0.1.0"
authors = ["Edwin Cox <https://github.com/edwin-cox>"]
license = "MIT"
description = "A simple 2-columns CV template close to Typst standard formatting"
categories = ["cv"]
keywords = ["CV", "Curriculum Vitae", "Resume", "Minimal", "Professional"]
repository = "https://github.com/edwin-cox/typst-alpin-cv"
exclude = ["*.pdf"]
entrypoint = "package.typ"

[template]
path = "template"
entrypoint = "cv.typ"
thumbnail = "thumbnail.png"
